# Generated by Django 4.2.1 on 2023-05-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='MY_BLOG_SHANMUKH', max_length=255),
        ),
    ]
